server:
  port: 8000
spring:
  application:
    name: zhyanTest-provider-user
  datasource:
    url: jdbc:oracle:thin:@192.168.35.151:1521:orcl?createDatabaseIfNotExist=true
    username: c##root
    password: root
    jpa:
    database: Oracle
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
    hibernate:
    ddl-auto: update

#  jpa:
#    generate-ddl: false
#    show-sql: true
#    hibernate:
#      ddl-auto: none
#  datasource:                           # 指定数据源
#    platform: h2                        # 指定数据源类型
#    schema: classpath:schema.sql        # 指定h2数据库的建表脚本
#    data: classpath:data.sql            # 指定h2数据库的数据脚本
logging:                                # 配置日志级别，让hibernate打印出执行的SQL
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      instance:
        prefer-ip-address: true
