server:
  port: 8000


#https://www.jianshu.com/p/c23c82a8fcfc
spring:
  application:
    name: zhyanTest-provider-user
  datasource:
    url: jdbc:oracle:thin:@192.168.1.112:1521:orcl?createDatabaseIfNotExist=true
    username: c##root
    password: root
  jpa:
    database: Oracle
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
    hibernate:
      ddl-auto: update
#
#spring:
#  application:
#    name: zhyanTest-provider-user
#  datasource:
#    url: jdbc:mysql://localhost:3306/zhyanTest?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
#    username: root
#    password: root
#  jpa:
#    database: MySQL
#    database-platform: org.hibernate.dialect.MySQLDialect
#    show-sql: true
#    hibernate:
#      ddl-auto: update



logging:                                # 配置日志级别，让hibernate打印出执行的SQL
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      instance:
        prefer-ip-address: true
