
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/,http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true


spring:
  application:
    name: zhyanTest-discovery-eureka-service1

server:
  port: 8761


